Updating for v9: update dependencies and run linter
pinojs/json-colorizer pull request #6
Opened 2023-09-14 13:46 UTC by Ranieri93

Hello!
Here I updated all dependencies that were outdated, and tests ran as expected.
As @jsumners mentioned, we could have a problem with deps switching to ESM-only, but to be honest I did not find a way of programmatically understanding if they are or not, so if you have any suggestions please share!

2023-09-14 21:28 UTC, jsumners requested changes

2023-09-14 21:28 UTC, jsumners commented on package-lock.json
Please do not include this file.

2023-09-15 07:22 UTC, Ranieri93 commented on package-lock.json
Hey yes, that's what I thought as well. But the CI was failing complaining that the package-lock.json was missing, so I commit it again and it went through. Let me delete it

2023-09-15 07:30 UTC, Ranieri93 commented on package-lock.json
`Error: Dependencies lock file is not found in /home/runner/work/json-colorizer/json-colorizer.`
I supposed that I needed to resolve this by adding the file, but I am a complete newbie to Actions in general, so I'll wait for your suggestions!

2023-09-15 13:17 UTC, jsumners commented on package-lock.json
The issue is this line in the CI config -- https://github.com/pinojs/json-colorizer/blob/3eff43c0ede8ede4f02027268825e30fcbd47d63/.github/workflows/ci.yaml#L29

As part of this PR, remove that line in the CI config.

2023-09-15 13:22 UTC, jsumners approved these changes
Looks good to me.

2023-09-15 13:23 UTC, merged